### ISSUE TITLE
Tutorial of Extending The Package

### ISSUE THREAD

**Issue by zhanghang1989** [wkcn/MobulaOP#1]
This is really nice work! It would be great if there is a tutorial of extending this package. Something like PyTorch Extension package http://hangzh.com/PyTorch-Encoding/notes/extending.html

**Comment by wkcn** [comment]
Hello! I have written [a tutorial in English](https://github.com/wkcn/MobulaOP/blob/master/docs/tutorial-en.md).
Sorry, it took a long time.

Thank you!
