### ISSUE TITLE
CustomOp in python and C++ for prediction

### ISSUE THREAD

**Issue by nuaawzl** [wkcn/MobulaOP#3]
Hello, it's very useful! I have a problem, I define a custom operator in mxnet(python) and get a model. Now I want to load the model(.json & .params ) by mxnet(C++). Can you give me some advice? thanks.

**Comment by wkcn** [comment]
Do you want to load the parameters in C++?
I think you can try the function
```c++
MXNET_DLL int MXNDArrayLoad(const char* fname,
                            mx_uint *out_size,
                            NDArrayHandle** out_arr,
                            mx_uint *out_name_size,
                            const char*** out_names);
```

 in [$MXNET_HOME/include/mxnet/c_api.h](https://github.com/apache/incubator-mxnet/blob/master/include/mxnet/c_api.h#L521).

**Comment by nuaawzl** [comment]
Thanks, I want to load the symbol and parameters in C++. But the model use a custom operator. MXNet C++ has no the operator, so I can't load the json file.

**Comment by wkcn** [comment]
@nuaawzl 
I found MXSymbolCreateFromFile is used to load all symbols, including Custom Operator.
And the custom operator is registered in [python/mxnet/operator.py](https://github.com/apache/incubator-mxnet/blob/master/python/mxnet/operator.py#L692).

I think it may be a solution.
1. get [creator_func](https://github.com/apache/incubator-mxnet/blob/master/python/mxnet/operator.py#L1095) of the custom operator in Python
2. use MXCustomOpRegister to register the custom operator in C++
3. use MXSymbolCreateFromFile to load all symbols in C++

**Comment by nuaawzl** [comment]
Thank you very much. I coded the new operator and recompiled mxnet. I'll try your advice.
