### ISSUE TITLE
Does it work if custom op and the framework are compiled with different version of GCC? 

### ISSUE THREAD

**Issue by eric-haibin-lin** [wkcn/MobulaOP#33]
MXNet pip package is built with gcc4. I wonder when Mobula ops are compiled (without MXNet source code) with gcc5, would it still work?

**Comment by wkcn** [comment]
Yes, it works.
I test it where MXNet is installed by pip and MobulaOP is compiled with gcc5/6/7/8 and clang++7.

MobulaOP only calls MXNet C API (`MXNDArrayGetData`, `MXNDArrayWaitToRead` and `MXNDArrayWaitToWrite`).
