### ISSUE TITLE
[Feature request] Gradient check

### ISSUE THREAD

**Issue by YutingZhang** [wkcn/MobulaOP#37]
It will be great if the package could provide a gradient checking tool.

**Comment by wkcn** [comment]
Thanks for your suggestion!
I will add it later : )

**Comment by wkcn** [comment]
Hi @YutingZhang , I have added the `mobula.testing.gradcheck` function in PR #54   : )

**Comment by wkcn** [comment]
Close it since `gradcheck` has been added : )
