### ISSUE TITLE
Question on ATTEN SAMPLER based on MobulaOP

### ISSUE THREAD

**Issue by AlexHu123** [wkcn/MobulaOP#60]
Hi, will you release the PyTorch version? And will it support multi-gpu training?

**Comment by wkcn** [comment]
Sorry that I will not release the PyTorch version, since I'm busy now.

**Comment by wkcn** [comment]
The PyTorch version has been released.
https://github.com/wkcn/AttentionSampler

**Comment by wkcn** [comment]
Close it because the same issue in https://github.com/wkcn/AttentionSampler/issues/2
