### ISSUE TITLE
where to find these keywords of mxnet

### ISSUE THREAD

**Issue by z01nl1o02** [wkcn/MobulaOP#7]
hi
 i am learning from your project and want to where to find these keywords of mxnet?

like those in check_backend(b):
    func_names = ['get_pointer', 'dev_id', 'wait_to_read', 'wait_to_write', 'OpGen']
is there any pages online about meanings of these keywords?

**Comment by wkcn** [comment]
I'm sorry that I haven't written the document of MobulaOP yet.

['get_pointer', 'dev_id', 'wait_to_read', 'wait_to_write', 'OpGen'] is the variables of MobulaOP.

get_pointer(v):
    v: ndarray
    return the raw data pointer of the ndarray `v`

dev_id(a):
    a: ndarray
    return the device id of the ndarray 'a'
    if the ndarray `a` is a CPU context, return None
    if the ndarray `a` is a GPU context, return GPU id

wait_to_read(variables):
  variables: the list of variables
  the function will be executed before variables are read.

wait_to_write(variables):
  variables: the list of variables
  the function will be executed before variables are written.

OpGen: Define a MobulaOP template

**Comment by z01nl1o02** [comment]
thanks a lot and i will try more!

**Comment by wkcn** [comment]
@z01nl1o02 
Thank you for your support! 
Feel free to re-open if there are similar issues. :-)
