### ISSUE TITLE
compile error

### ISSUE THREAD

**Issue by chop2** [wkcn/MobulaOP#72]
【python test_mul_func.py】，error occurs

[10:21:12] src/engine/engine.cc:55: MXNet start using engine: NaiveEngine
/wls/tf_workspace/MobulaOP/mobula/glue/mx.py:44: UserWarning: Using asynchronous execution for MXNet failed, since /home/weishuyi/anaconda3/lib/python3.7/site-packages/mxnet/libmxnet.so: undefined symbol: MXShallowCopyNDArray
It will drop the performance.
Recommend using the latest version of MXNet
  Recommend using the latest version of MXNet""".format(e))
mkdir -p /wls/tf_workspace/MobulaOP/mobula/build/cpu/src
g++ /wls/tf_workspace/MobulaOP/mobula/src/defines.cpp -std=c++11 -DUSING_CUDA=0 -DUSING_HIP=0 -DUSING_OPENMP=0  -DHOST_NUM_THREADS=40 -O3 -DUSING_CBLAS=0 -I/wls/tf_workspace/MobulaOP/mobula/./ -I/wls/tf_workspace/MobulaOP/mobula/./inc -I/wls/tf_workspace/MobulaOP/mobula/../3rdparty/dlpack/include -I/wls/tf_workspace/MobulaOP/mobula/../3rdparty/tvm_packed_func -fPIC -Werror -Wall -Wextra -pedantic -Wcast-align -Wcast-qual -Wctor-dtor-privacy -Wdisabled-optimization -Wformat=2 -Winit-self -Wmissing-include-dirs -Wold-style-cast -Woverloaded-virtual -Wredundant-decls -Wshadow -Wsign-promo -Wundef -fdiagnostics-show-option -c -o /wls/tf_workspace/MobulaOP/mobula/build/cpu/src/defines.o
g++ /wls/tf_workspace/MobulaOP/mobula/src/context.cpp -std=c++11 -DUSING_CUDA=0 -DUSING_HIP=0 -DUSING_OPENMP=0  -DHOST_NUM_THREADS=40 -O3 -DUSING_CBLAS=0 -I/wls/tf_workspace/MobulaOP/mobula/./ -I/wls/tf_workspace/MobulaOP/mobula/./inc -I/wls/tf_workspace/MobulaOP/mobula/../3rdparty/dlpack/include -I/wls/tf_workspace/MobulaOP/mobula/../3rdparty/tvm_packed_func -fPIC -Werror -Wall -Wextra -pedantic -Wcast-align -Wcast-qual -Wctor-dtor-privacy -Wdisabled-optimization -Wformat=2 -Winit-self -Wmissing-include-dirs -Wold-style-cast -Woverloaded-virtual -Wredundant-decls -Wshadow -Wsign-promo -Wundef -fdiagnostics-show-option -c -o /wls/tf_workspace/MobulaOP/mobula/build/cpu/src/context.o
mkdir -p MulElemWise/build/MulElemWise/build/cpu
g++ MulElemWise/build/cpu/MulElemWise_wrapper.cpp -std=c++11 -DUSING_CUDA=0 -DUSING_HIP=0 -DUSING_OPENMP=0  -DHOST_NUM_THREADS=40 -O3 -DUSING_CBLAS=0 -I/wls/tf_workspace/MobulaOP/mobula/./ -I/wls/tf_workspace/MobulaOP/mobula/./inc -I/wls/tf_workspace/MobulaOP/mobula/../3rdparty/dlpack/include -I/wls/tf_workspace/MobulaOP/mobula/../3rdparty/tvm_packed_func -fPIC -Werror -Wall -Wextra -pedantic -Wcast-align -Wcast-qual -Wctor-dtor-privacy -Wdisabled-optimization -Wformat=2 -Winit-self -Wmissing-include-dirs -Wold-style-cast -Woverloaded-virtual -Wredundant-decls -Wshadow -Wsign-promo -Wundef -fdiagnostics-show-option -c -o MulElemWise/build/MulElemWise/build/cpu/MulElemWise_wrapper.o
In file included from /wls/tf_workspace/MobulaOP/mobula/./inc/mobula_op.h:5:0,
                 from MulElemWise/build/cpu/MulElemWise_wrapper.cpp:8:
/wls/tf_workspace/MobulaOP/mobula/./inc/glue_mx.h: In function ‘void RegisterMXAPI(void*, void*, void*, void*, void*)’:
/wls/tf_workspace/MobulaOP/mobula/./inc/glue_mx.h:45:76: error: ISO C++ forbids casting between pointer-to-function and pointer-to-object [-Werror=pedantic]
       reinterpret_cast<decltype(MXShallowCopyNDArray)>(shallow_copy_ndarray);
                                                                            ^
/wls/tf_workspace/MobulaOP/mobula/./inc/glue_mx.h:46:73: error: ISO C++ forbids casting between pointer-to-function and pointer-to-object [-Werror=pedantic]
   MXNDArrayFree = reinterpret_cast<decltype(MXNDArrayFree)>(ndarray_free);
                                                                         ^
/wls/tf_workspace/MobulaOP/mobula/./inc/glue_mx.h:48:74: error: ISO C++ forbids casting between pointer-to-function and pointer-to-object [-Werror=pedantic]
       reinterpret_cast<decltype(MXNDArrayGetContext)>(ndarray_get_context);
                                                                          ^
/wls/tf_workspace/MobulaOP/mobula/./inc/glue_mx.h:50:70: error: ISO C++ forbids casting between pointer-to-function and pointer-to-object [-Werror=pedantic]
       reinterpret_cast<decltype(MXNDArrayToDLPack)>(ndarray_to_dlpack);
                                                                      ^
/wls/tf_workspace/MobulaOP/mobula/./inc/glue_mx.h:52:73: error: ISO C++ forbids casting between pointer-to-function and pointer-to-object [-Werror=pedantic]
       reinterpret_cast<decltype(MXEnginePushSyncND)>(engine_push_sync_nd);

**Comment by wkcn** [comment]
`MXShallowCopyNDArray` only exists in the high version of MXNet.
Please use MXNet 1.6 or higher version : )

**Comment by wkcn** [comment]
Thank you for the report. I will check it.

**Comment by chop2** [comment]
【gcc version】
gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-4)
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

**Comment by wkcn** [comment]
Hi @chop2 , the bug may have been fixed.
Please update the code of MobulaOP from its master branch.

To enable the asynchronous execution of MXNet to get faster performance, please update MXNet to 1.6 or higher version.

**Comment by chop2** [comment]
thxs, it work's :)
